import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import queryPackageTransactionBlock from '../server/quertPackageTransaction';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
        // 由于 await 只能在异步函数中使用，因此将 useEffect 回调函数改为异步函数
        queryPackageTransactionBlock().then(() => {
          // 可在此处添加查询成功后的处理逻辑
        }).catch((error) => {
          console.error('查询包交易块时出错:', error);
        });
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
